<?php
// auto-generated by sfPropelCrud
// date: 2007/08/14 12:22:08
?>
<h1>alumno</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Confirmado</th>
  <th>Borrado</th>
  <th>Nombreusuario</th>
  <th>Sha1 password</th>
  <th>Salt</th>
  <th>Dni</th>
  <th>Nombre</th>
  <th>Apellidos</th>
  <th>Email</th>
  <th>Emailstop</th>
  <th>Telefono1</th>
  <th>Telefono2</th>
  <th>Institucion</th>
  <th>Departamento</th>
  <th>Direccion</th>
  <th>Cp</th>
  <th>Ciudad</th>
  <th>Pais</th>
  <th>Ultimoacceso</th>
  <th>Ultimaip</th>
  <th>Secreto</th>
  <th>Foto</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($usuarios as $usuario): ?>
<tr>
    <td><?php echo link_to($usuario->getId(), 'usuario/show?id='.$usuario->getId()) ?></td>
      <td><?php echo $usuario->getConfirmado() ?></td>
      <td><?php echo $usuario->getBorrado() ?></td>
      <td><?php echo $usuario->getNombreusuario() ?></td>
      <td><?php echo $usuario->getSha1Password() ?></td>
      <td><?php echo $usuario->getSalt() ?></td>
      <td><?php echo $usuario->getDni() ?></td>
      <td><?php echo $usuario->getNombre() ?></td>
      <td><?php echo $usuario->getApellidos() ?></td>
      <td><?php echo $usuario->getEmail() ?></td>
      <td><?php echo $usuario->getEmailstop() ?></td>
      <td><?php echo $usuario->getTelefono1() ?></td>
      <td><?php echo $usuario->getTelefono2() ?></td>
      <td><?php echo $usuario->getInstitucion() ?></td>
      <td><?php echo $usuario->getDepartamento() ?></td>
      <td><?php echo $usuario->getDireccion() ?></td>
      <td><?php echo $usuario->getCp() ?></td>
      <td><?php echo $usuario->getCiudad() ?></td>
      <td><?php echo $usuario->getPais() ?></td>
      <td><?php echo $usuario->getUltimoacceso() ?></td>
      <td><?php echo $usuario->getUltimaip() ?></td>
      <td><?php echo $usuario->getSecreto() ?></td>
      <td><?php echo $usuario->getFoto() ?></td>
      <td><?php echo $usuario->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'usuario/create') ?>
