<?php
// auto-generated by sfPhpConfigHandler
// date: 2018/09/19 16:08:18
ini_set('log_errors', '1');
ini_set('arg_separator.output', '&amp;');
if (ini_get('session.auto_start') != false)
{
  sfLogger::getInstance()->warning('{sfPhpConfigHandler} php.ini "session.auto_start" key is better set to "false" (current value is "\'0\'" - php.ini location: "C:\wamp\bin\apache\apache2.2.22\bin\php.ini")');
}

