<?php
// auto-generated by sfRoutingConfigHandler
// date: 2018/09/19 16:08:18
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'comercial',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sf_captcha' => 
  array (
    0 => '/captcha',
    1 => '#^/captcha\\.jpg$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfCaptcha',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '.jpg',
  ),
  'foro_home' => 
  array (
    0 => '/foro/',
    1 => '#^/foro/$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'forumList',
    ),
    5 => 
    array (
    ),
    6 => '/',
  ),
  'foro_ultimos_mensajes' => 
  array (
    0 => '/foro/ultimos',
    1 => '#^/foro/ultimos$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'latestPosts',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'foro_foro' => 
  array (
    0 => '/foro/:forum_name',
    1 => '#^/foro(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'forum_name',
    ),
    3 => 
    array (
      'forum_name' => 1,
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'forum',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'foro_ultimos_mensajes_para_foro' => 
  array (
    0 => '/foro/:forum_name/ultimos',
    1 => '#^/foro(?:\\/([^\\/]+))?/ultimos$#',
    2 => 
    array (
      0 => 'forum_name',
    ),
    3 => 
    array (
      'forum_name' => 1,
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'latestPosts',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'foro_hilo' => 
  array (
    0 => '/foro/hilo/:id/:stripped_title',
    1 => '#^/foro/hilo(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
      1 => 'stripped_title',
    ),
    3 => 
    array (
      'id' => 1,
      'stripped_title' => 1,
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'topic',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'foro_ultimos_mensajes_por_usuario' => 
  array (
    0 => '/foro/usuario/:nombreusuario',
    1 => '#^/foro/usuario(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'nombreusuario',
    ),
    3 => 
    array (
      'nombreusuario' => 1,
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'latestUserPosts',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'foro_mensaje' => 
  array (
    0 => '/foro/mensaje/:id',
    1 => '#^/foro/mensaje(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
    ),
    3 => 
    array (
      'id' => 1,
    ),
    4 => 
    array (
      'module' => 'sfSimpleForum',
      'action' => 'post',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
