<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/19 16:08:18
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'alumno',
        1 => 'profesor',
        2 => 'supervisor',
      ),
    ),
  ),
);
