index:
  is_secure:   on                # Sólo para usuarios autenticados
  credentials: [[ alumno, profesor, supervisor ]]

RankingModulo:
  is_secure:    on
  credentials: [ supervisor ]

seguimientoTemas:
  is_secure:    on
  credentials: [[ profesor, supervisor ]]

seguimientoTiempos:
  is_secure: on
  credential: [[administrador]]

auditoriaSRE:
  is_secure: on
  credential: [[administrador]]

all:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor, administrador]]