verFicheroSuccess:
  stylesheets: [-*]


default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        <?php echo sfConfig::get('app_lms_nombre')."\n"; ?>
    robots:       index, follow
    description:  plataforma de formacion online <?php echo sfConfig::get('app_lms_nombre')."\n"; ?>
    keywords:     e-learning, plataforma
    language:     es

  javascripts:    [ events ]

  stylesheets:    [ main ]

  has_layout:     on
  layout:         layout

  components:
    menu:      [menu, default]
    menu_top:  [menu_top, default]
    submenu: [submenu, default]
    calendario: [calendario, default]
    aviso: [aviso, default]
    login: [login, default]

chatlayout:
  http_metas:
    content-type: text/html; charset=utf-8