<?php
// auto-generated by sfPropelCrud
// date: 2007/08/02 11:54:44
?>
<h1>materia</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Nombre</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($materias as $materia): ?>
<tr>
    <td><?php echo link_to($materia->getId(), 'materia/show?idcurso='.$materia->getId()) ?></td>
      <td><?php echo $materia->getNombre() ?></td>
      <td><?php echo $materia->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'materia/create') ?>
