<?php
// auto-generated by sfPropelCrud
// date: 2007/08/02 11:54:44
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $materia->getId() ?></td>
</tr>
<tr>
<th>Nombre: </th>
<td><?php echo $materia->getNombre() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $materia->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'materia/edit?idcurso='.$materia->getId()) ?>
&nbsp;<?php echo link_to('list', 'materia/list') ?>
