index:
  is_secure:   on                # Sólo para usuarios autenticados
  credentials: [[ alumno, profesor, supervisor, administrador]]

nuevoLibro:
  is_secure:   on
  credentials: profesor

eliminarLibro:
  is_secure:   on
  credentials: profesor

modificarLibro:
  is_secure:   on
  credentials: profesor

fichaCurso:
  is_secure:   on
  credentials: [[supervisor, administrador]]

modificarNormativa:
  is_secure:    on
  credentials: profesor

all:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor, administrador]]