<?php
// auto-generated by sfPropelCrud
// date: 2007/08/02 11:55:19
?>
<?php use_helper('Object') ?>

<?php echo form_tag('curso/update') ?>

<?php echo object_input_hidden_tag($curso, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($curso, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Fecha inicio:</th>
  <td><?php echo object_input_date_tag($curso, 'getFechaInicio', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Fecha fin:</th>
  <td><?php echo object_input_date_tag($curso, 'getFechaFin', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Materia:</th>
  <td><?php echo object_select_tag($curso, 'getMateriaId', array (
  'related_class' => 'Materia',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($curso->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'curso/delete?id='.$curso->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'curso/show?id='.$curso->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'curso/list') ?>
<?php endif; ?>
</form>
