<?php
// auto-generated by sfPropelCrud
// date: 2007/08/02 11:55:20
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $curso->getId() ?></td>
</tr>
<tr>
<th>Nombre: </th>
<td><?php echo $curso->getNombre() ?></td>
</tr>
<tr>
<th>Fecha inicio: </th>
<td><?php echo $curso->getFechaInicio() ?></td>
</tr>
<tr>
<th>Fecha fin: </th>
<td><?php echo $curso->getFechaFin() ?></td>
</tr>
<tr>
<th>Materia: </th>
<td><?php echo $curso->getMateriaId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $curso->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'curso/edit?id='.$curso->getId()) ?>
&nbsp;<?php echo link_to('list', 'curso/list') ?>
