index:
  is_secure:   on                # Sólo para usuarios autenticados
  credentials: [[ alumno, profesor, supervisor, administrador ]]

all:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor, administrador ]]