cambiarTareas:
  is_secure:   on
  credentials: profesor

modificarTarea:
  is_secure:   on
  credentials: profesor

cancelarTarea:
  is_secure:   on
  credentials: profesor

listarEjerciciosExamen:
  is_secure:   on
  credentials: profesor
  
listarTareas:
  is_secure:   on
  credentials: profesor
  
mostrarTarea:
  is_secure:   on
  credentials: profesor
  
tareasExamenes:
  is_secure:   on
  credentials: profesor

tareasExamenesPaso2:
  is_secure:   on
  credentials: profesor

tareasExamenesPaso3:
  is_secure:   on
  credentials: profesor
  
tareasExamenesPaso4:
  is_secure:   on
  credentials: profesor

tareasExamenesFin:
  is_secure:   on
  credentials: profesor

historialEntregas:
  is_secure:   on
  credentials: alumno
  
listarHistorialEntregas:
  is_secure:   on
  credentials: alumno

tareasPendientes:
  is_secure:   on
  credentials: alumno

listarTareasPendientes:
  is_secure:   on
  credentials: alumno

mostrarEjercicioTarea:
  is_secure:   on
  credentials: alumno

resolverEjercicioTarea:
  is_secure:   on
  credentials: alumno
  
entregarTarea:
  is_secure:   on
  credentials: alumno
  
guardarResultadosTarea:
  is_secure:   on
  credentials: alumno

all:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor ]]
