<?php
// auto-generated by sfPropelCrud
// date: 2007/08/02 11:55:20
?>
<h1>curso</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Nombre</th>
  <th>Fecha inicio</th>
  <th>Fecha fin</th>
  <th>Materia</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($cursos as $curso): ?>
<tr>
    <td><?php echo link_to($curso->getId(), 'curso/show?id='.$curso->getId()) ?></td>
      <td><?php echo $curso->getNombre() ?></td>
      <td><?php echo $curso->getFechaInicio() ?></td>
      <td><?php echo $curso->getFechaFin() ?></td>
      <td><?php echo $curso->getMateriaId() ?></td>
      <td><?php echo $curso->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'curso/create') ?>
