all:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype]
  components:
    menu: [menu, variable]
    menu_top: [menu_top, variable]

sf_captcha:
  has_layout:     off
  http-metas:     content-type: image/jpeg

confirmacionSuccess:
  has_layout:     off
