# default rules
homepage:
  url:   /
  param: { module: <?php echo sfConfig::get('app_core_minicial'); ?>, action: <?php echo sfConfig::get('app_core_ainicial'); ?> }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_captcha:
  url:   /captcha.jpg
  param: { module: sfCaptcha, action: index }

#########################
# Reglas para el foro ###
#########################

foro_home:
  url:   /foro/
  param: { module: sfSimpleForum, action: forumList }

#foro_home:
#  url:   /foro/:forum_name
#  param: { module: sfSimpleForum, action: forum }

#sfSimpleForum/forum/forum_name/curso-de-fisica

foro_ultimos_mensajes:
  url:   /foro/ultimos
  param: { module: sfSimpleForum, action: latestPosts }

foro_foro:
  url:   /foro/:forum_name
  param: { module: sfSimpleForum, action: forum }

foro_ultimos_mensajes_para_foro:
  url:   /foro/:forum_name/ultimos
  param: { module: sfSimpleForum, action: latestPosts }

foro_hilo:
  url:   /foro/hilo/:id/:stripped_title
  param: { module: sfSimpleForum, action: topic }

foro_ultimos_mensajes_por_usuario:
  url:   /foro/usuario/:nombreusuario
  param: { module: sfSimpleForum, action: latestUserPosts }

foro_mensaje:
  url:   /foro/mensaje/:id
  param: { module: sfSimpleForum, action: post }


