<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/09/18 20:30:04

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => 'localhost',
  'database' => 'ceep_ceep',
  'username' => 'ceep_ceep',
  'password' => 'Adra1000',
  'encoding' => 'utf8',
), 'propel');
$this->databases['propel'] = $database;
