<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/18 21:33:34
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'alumno',
        1 => 'profesor',
        2 => 'supervisor',
        3 => 'examinandose',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'alumno',
        1 => 'profesor',
        2 => 'supervisor',
        3 => 'administrador',
        4 => 'examinandose',
      ),
    ),
  ),
  'crearEjercicio' => 
  array (
    'is_secure' => true,
    'credentials' => 'profesor',
  ),
  'editarCuestionCorta' => 
  array (
    'is_secure' => true,
    'credentials' => 'profesor',
  ),
  'editarCuestionTest' => 
  array (
    'is_secure' => true,
    'credentials' => 'profesor',
  ),
  'editarEjercicio' => 
  array (
    'is_secure' => true,
    'credentials' => 'profesor',
  ),
);
