<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/20 23:09:22
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 'supervisor',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'supervisor',
  ),
);
