<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/18 21:29:44
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'alumno',
        1 => 'profesor',
        2 => 'supervisor',
        3 => 'administrador',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'alumno',
        1 => 'profesor',
        2 => 'supervisor',
        3 => 'administrador',
      ),
    ),
  ),
);
