<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/18 21:29:34
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 'alumno',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'alumno',
  ),
);
