<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/18 20:30:22
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 'profesor',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'profesor',
  ),
);
