<?php
// auto-generated by sfValidatorConfigHandler
// date: 2018/09/18 20:30:21

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['nombreusuarioValidator'] = new sfStringValidator();
  $validators['nombreusuarioValidator']->initialize($context, array (
  'min' => 5,
  'min_error' => 'el nombre de usuario debe contener al menos 5 caracteres',
));
  $validators['usuarioValidator'] = new myLoginValidator();
  $validators['usuarioValidator']->initialize($context, array (
  'password' => 'password',
  'login_error' => 'la cuenta especificada no existe o ha introducido una contrase&ntilde;a incorrecta',
));
  $validatorManager->registerName('nombreusuario', 1, 'introduce tu nombre de usuario', null, null, false);
  $validatorManager->registerValidator('nombreusuario', $validators['nombreusuarioValidator'], null);
  $validatorManager->registerValidator('nombreusuario', $validators['usuarioValidator'], null);
  $validatorManager->registerName('password', 1, 'introduce tu password', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
