index:
  is_secure:   on                # Sólo para usuarios autenticados
  credentials: [[ alumno, profesor ]]  # Con credencial "alumno"

all:
  is_secure:    on
  credentials:  [[ alumno, profesor ]]