index:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor, administrador ]]

mostrarPerfil:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor, administrador, moroso ]]

all:
  is_secure:    on
  credentials:  [[ alumno, profesor, supervisor, administrador ]]
